/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.ui;

import com.mysql.cj.protocol.Message;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.example.model.InfoUser;
import org.example.model.StocBilete;
import org.example.services.SystemDeliveryReceive;



/**
 *
 * @author cadfrunze
 */
public class TicketsSystemManagement extends javax.swing.JFrame {

    /**
     * Creates new form TicketsSystemManagement
     */
    private SystemDeliveryReceive sdr;
    private List<StocBilete> lista;
    private int idEvClient;
    
    public TicketsSystemManagement() throws SQLException, ClassNotFoundException {
        sdr = new SystemDeliveryReceive();
        initComponents();
    }
    
    public TicketsSystemManagement(SystemDeliveryReceive sdr) throws SQLException, ClassNotFoundException{
        this.sdr = sdr;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        JPanelDate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tab1TfPrenume = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        tab1TfCnp = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        tab1TfTelefon = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        tab1TfNume = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        tab1TfEmail = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tab1LbAv = new javax.swing.JLabel();
        jPanelBilete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tab1ComboIteme = new javax.swing.JComboBox<>();
        tab1LbCantitate = new javax.swing.JLabel();
        tab1BtnPlateste = new javax.swing.JButton();
        tab2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tab2Tf1 = new javax.swing.JTextField();
        tab2Tf2 = new javax.swing.JTextField();
        tab2Tf3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tab2TfCnp = new javax.swing.JTextField();
        tab2ButtVerifica = new javax.swing.JButton();
        tab2Jpanel = new javax.swing.JPanel();
        tab2LbNume = new javax.swing.JLabel();
        tab2LbPrenume = new javax.swing.JLabel();
        tab2EmailTf = new javax.swing.JTextField();
        tab2TelefonTf = new javax.swing.JTextField();
        tab2BtnDelete = new javax.swing.JButton();
        tab2BtnSave1 = new javax.swing.JButton();
        tab2BtnActiveaza = new javax.swing.JButton();
        tab2RaspLb = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 650));
        setResizable(false);

        jLabel1.setText("Powered by CadFrunze");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CNP");
        jLabel4.setAlignmentY(2.0F);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Telefon");
        jLabel6.setAlignmentY(2.0F);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Prenume");
        jLabel3.setAlignmentY(2.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nume");
        jLabel2.setAlignmentY(2.0F);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        jLabel5.setAlignmentY(2.0F);

        tab1TfPrenume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tab1TfPrenumeFocusLost(evt);
            }
        });
        tab1TfPrenume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tab1TfPrenumeKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(tab1TfPrenume);
        tab1TfPrenume.getAccessibleContext().setAccessibleParent(JPanelDate);

        tab1TfCnp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tab1TfCnpFocusLost(evt);
            }
        });
        tab1TfCnp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tab1TfCnpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tab1TfCnpKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(tab1TfCnp);
        tab1TfCnp.getAccessibleContext().setAccessibleParent(JPanelDate);

        jScrollPane9.setViewportView(tab1TfTelefon);
        tab1TfTelefon.getAccessibleContext().setAccessibleParent(JPanelDate);

        tab1TfNume.setToolTipText("");
        tab1TfNume.setMaximumSize(new java.awt.Dimension(62, 20));
        tab1TfNume.setName(""); // NOI18N
        tab1TfNume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tab1TfNumeFocusLost(evt);
            }
        });
        tab1TfNume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tab1TfNumeKeyTyped(evt);
            }
        });
        jScrollPane10.setViewportView(tab1TfNume);
        tab1TfNume.getAccessibleContext().setAccessibleParent(JPanelDate);

        tab1TfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tab1TfEmailFocusLost(evt);
            }
        });
        tab1TfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tab1TfEmailKeyTyped(evt);
            }
        });
        jScrollPane11.setViewportView(tab1TfEmail);
        tab1TfEmail.getAccessibleContext().setAccessibleParent(JPanelDate);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        tab1LbAv.setForeground(new java.awt.Color(255, 0, 51));
        tab1LbAv.setToolTipText("");

        javax.swing.GroupLayout JPanelDateLayout = new javax.swing.GroupLayout(JPanelDate);
        JPanelDate.setLayout(JPanelDateLayout);
        JPanelDateLayout.setHorizontalGroup(
            JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelDateLayout.createSequentialGroup()
                        .addComponent(tab1LbAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(JPanelDateLayout.createSequentialGroup()
                        .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        JPanelDateLayout.setVerticalGroup(
            JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(JPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab1LbAv, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanelBilete.setVisible(false);
        jPanelBilete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 5, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selecteaza Tip Bilet");

        tab1ComboIteme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tab1ComboIteme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tab1ComboItemeItemStateChanged(evt);
            }
        });
        tab1ComboIteme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1ComboItemeMouseClicked(evt);
            }
        });

        tab1LbCantitate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tab1LbCantitate.setToolTipText("");

        tab1BtnPlateste.setBackground(new java.awt.Color(0, 102, 255));
        tab1BtnPlateste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tab1BtnPlateste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1BtnPlatesteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBileteLayout = new javax.swing.GroupLayout(jPanelBilete);
        jPanelBilete.setLayout(jPanelBileteLayout);
        jPanelBileteLayout.setHorizontalGroup(
            jPanelBileteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBileteLayout.createSequentialGroup()
                .addGroup(jPanelBileteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBileteLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanelBileteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tab1ComboIteme, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBileteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tab1BtnPlateste, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(tab1LbCantitate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelBileteLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelBileteLayout.setVerticalGroup(
            jPanelBileteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBileteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1ComboIteme, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(tab1LbCantitate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(tab1BtnPlateste, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBilete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(JPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelBilete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buy Ticket", tab1);
        tab1.getAccessibleContext().setAccessibleName("");

        jLabel12.setText("Serie ticket");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CNP");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("-");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("-");

        tab2ButtVerifica.setBackground(new java.awt.Color(0, 153, 204));
        tab2ButtVerifica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tab2ButtVerifica.setText("Verifica/Editeaza!");
        tab2ButtVerifica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tab2ButtVerifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2ButtVerificaActionPerformed(evt);
            }
        });

        tab2Jpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tab2LbNume.setText("Nume: ");

        tab2LbPrenume.setText("Prenume: ");

        tab2BtnDelete.setBackground(new java.awt.Color(255, 0, 0));
        tab2BtnDelete.setText("Delete!");
        tab2BtnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tab2BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2BtnDeleteActionPerformed(evt);
            }
        });

        tab2BtnSave1.setBackground(new java.awt.Color(0, 153, 255));
        tab2BtnSave1.setText("Save");
        tab2BtnSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tab2BtnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2BtnSave1ActionPerformed(evt);
            }
        });

        tab2BtnActiveaza.setBackground(new java.awt.Color(51, 51, 255));
        tab2BtnActiveaza.setText("Activeaza!");
        tab2BtnActiveaza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tab2BtnActiveaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2BtnActiveazaActionPerformed(evt);
            }
        });

        tab2RaspLb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab2RaspLb.setText("Bilet: ");

        jLabel16.setText("Email");

        jLabel17.setText("Telefon");

        javax.swing.GroupLayout tab2JpanelLayout = new javax.swing.GroupLayout(tab2Jpanel);
        tab2Jpanel.setLayout(tab2JpanelLayout);
        tab2JpanelLayout.setHorizontalGroup(
            tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2JpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2JpanelLayout.createSequentialGroup()
                                .addComponent(tab2BtnActiveaza, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2JpanelLayout.createSequentialGroup()
                                .addGroup(tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tab2BtnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tab2BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2JpanelLayout.createSequentialGroup()
                                .addComponent(tab2RaspLb, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))))
                    .addGroup(tab2JpanelLayout.createSequentialGroup()
                        .addComponent(tab2LbNume, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tab2LbPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab2JpanelLayout.createSequentialGroup()
                                .addComponent(tab2EmailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tab2TelefonTf))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2JpanelLayout.createSequentialGroup()
                                .addGap(0, 11, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
        );
        tab2JpanelLayout.setVerticalGroup(
            tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2JpanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab2JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tab2LbNume)
                    .addComponent(tab2LbPrenume)
                    .addComponent(tab2EmailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab2TelefonTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab2RaspLb, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tab2BtnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tab2BtnActiveaza, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(tab2Tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tab2Tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tab2TfCnp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tab2Tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(tab2ButtVerifica, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tab2Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(tab2Tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tab2Tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(tab2Tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tab2TfCnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(tab2ButtVerifica, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(tab2Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit/Activate", tab2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // -----------------------------------------------------------------------TAB1------------------------------------------------------------------------------------------------------------
    private void tab1ComboItemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1ComboItemeMouseClicked
        // TODO add your handling code here:
        lista = this.sdr.getStocuriBilete();
        tab1ComboIteme.removeAllItems();
        for (StocBilete stoc: lista)
        {
            tab1ComboIteme.addItem(stoc.getTip_ticket());
        }
    }//GEN-LAST:event_tab1ComboItemeMouseClicked

    private void tab1ComboItemeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tab1ComboItemeItemStateChanged
        // TODO add your handling code here:
        //System.out.println(tab1ComboIteme.getSelectedItem());

        for (StocBilete selectat: lista)
        {
            if (selectat.getTip_ticket() == tab1ComboIteme.getSelectedItem())
            {
                tab1BtnPlateste.setVisible(true);
                tab1LbCantitate.setVisible(true);
                tab1LbCantitate.setText(MessageFormat.format("Cantitate: {0}", selectat.getCantitate()));
                tab1BtnPlateste.setText(String.format("Pret bilet: %s lei   Plateste!", selectat.getPret()));
            }
            
        }
    }//GEN-LAST:event_tab1ComboItemeItemStateChanged

    private void tab1TfEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab1TfEmailKeyTyped
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfEmailKeyTyped

    private void tab1TfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab1TfEmailFocusLost
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfEmailFocusLost

    private void tab1TfNumeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab1TfNumeKeyTyped
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfNumeKeyTyped

    private void tab1TfNumeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab1TfNumeFocusLost
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfNumeFocusLost

    private void tab1TfCnpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab1TfCnpKeyTyped
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfCnpKeyTyped

    private void tab1TfCnpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab1TfCnpKeyReleased
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfCnpKeyReleased

    private void tab1TfCnpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab1TfCnpFocusLost
        //System.out.println(tab1TfCnp.getText().toString());
        checkFielduri();
    }//GEN-LAST:event_tab1TfCnpFocusLost

    private void tab1TfPrenumeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tab1TfPrenumeKeyTyped
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfPrenumeKeyTyped

    private void tab1TfPrenumeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab1TfPrenumeFocusLost
        // TODO add your handling code here:
        checkFielduri();
    }//GEN-LAST:event_tab1TfPrenumeFocusLost

    private void tab1BtnPlatesteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1BtnPlatesteMouseClicked
        try {
            // TODO add your handling code here:
            sdr.sendNewUser(tab1TfNume.getText().strip().toLowerCase(),
                    tab1TfPrenume.getText().toLowerCase(),
                    tab1TfCnp.getText().strip().toLowerCase(),
                    tab1TfEmail.getText().strip().toLowerCase(),
                    tab1TfTelefon.getText().strip(), (String) tab1ComboIteme.getSelectedItem());
            JOptionPane.showMessageDialog(rootPane, "Ticket achizionat cu succes!. Vei primi un bon fiscal","Succes", JOptionPane.INFORMATION_MESSAGE);
            sdr.runScriptPython();
        } catch (SQLException ex) {
            Logger.getLogger(TicketsSystemManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanelBilete.setVisible(false);
        
    }//GEN-LAST:event_tab1BtnPlatesteMouseClicked

    //----------------------------------------------------------------------TAB2-----------------------------------------------------------------------------------
    void checkDate()
    {   
        tab2BtnActiveaza.setVisible(false);
        InfoUser infoUser = sdr.getInfoUser();
        this.idEvClient = infoUser.getIdEvClienti();
        if (infoUser.getIdEvClienti() != 0)
        {   
            tab2Jpanel.setVisible(true);
            tab2LbNume.setText("Nume: "+infoUser.getNume().toUpperCase());
            tab2LbPrenume.setText("Prenume: "+infoUser.getPrenume().toUpperCase());
            tab2EmailTf.setText(infoUser.getEmail());
            tab2TelefonTf.setText(infoUser.getTelefon());
            System.out.println(infoUser.getValidare());
            if ("0".equals(infoUser.getValidare()))
            {
                tab2RaspLb.setText("Bilet: NEVALIDAT!");
                tab2BtnActiveaza.setVisible(true);
            }
            else{tab2RaspLb.setText("Bilet: VALIDAT!");}
            
        }
        else
        {   
            tab2Jpanel.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "Nu te-am gasit in baza de date!","Fail", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    private void tab2ButtVerificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2ButtVerificaActionPerformed
        // TODO add your handling code here:
        sdr.sendInfoUser(tab2Tf1.getText().strip()+tab2Tf2.getText().strip()+tab2Tf3.getText().strip(), tab2TfCnp.getText().strip());
        checkDate();
        
    }//GEN-LAST:event_tab2ButtVerificaActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        tab2Jpanel.setVisible(false);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void tab2BtnActiveazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2BtnActiveazaActionPerformed
        // TODO add your handling code here:
        sdr.valideazaBilet(this.idEvClient);
        sdr.sendInfoUser(tab2Tf1.getText().strip()+tab2Tf2.getText().strip()+tab2Tf3.getText().strip(), tab2TfCnp.getText().strip());
        checkDate();
        JOptionPane.showMessageDialog(rootPane, "Bilet validat cu succes","Validat!", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_tab2BtnActiveazaActionPerformed

    private void tab2BtnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2BtnSave1ActionPerformed
        // TODO add your handling code here:
        sdr.updateUser(this.idEvClient, tab2EmailTf.getText().toLowerCase().strip(), tab2TelefonTf.getText().toLowerCase().strip());
        sdr.sendInfoUser(tab2Tf1.getText().strip()+tab2Tf2.getText().strip()+tab2Tf3.getText().strip(), tab2TfCnp.getText().strip());
        checkDate();
        JOptionPane.showMessageDialog(rootPane, "Validat!","Validat!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tab2BtnSave1ActionPerformed

    private void tab2BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2BtnDeleteActionPerformed
        // TODO add your handling code here:
        sdr.deleteUser(this.idEvClient);
        sdr.sendInfoUser(tab2Tf1.getText().strip()+tab2Tf2.getText().strip()+tab2Tf3.getText().strip(), tab2TfCnp.getText().strip());
        checkDate();
        JOptionPane.showMessageDialog(rootPane, "Utilizator sters cu succes!","Validat!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tab2BtnDeleteActionPerformed
    
    //------------------------------------------------------------------------EVENTURI DIN TAB1--------------------------------------------------------------------------------------
    void checkFielduri(){
        
            try {
            // TODO add your handling code here:
            this.sdr.cnpFind(tab1TfCnp.getText().strip());
            tab1LbAv.setText("");
            if (false == this.sdr.cnpFind(tab1TfCnp.getText().strip()))
            {
                if (tab1TfNume.getText().strip().length() < 3
                    || tab1TfPrenume.getText().strip().length() < 3
                    || tab1TfCnp.getText().strip().length() < 3
                    || tab1TfEmail.getText().strip().length() < 3
                    )
                    {
                        jPanelBilete.setVisible(false);
                        tab1LbAv.setText("Completeaza toate campurile cu * (minim 3 car.)");
                        
                    }
                else {
                    jPanelBilete.setVisible(true);
                    tab1BtnPlateste.setVisible(false);
                    tab1LbCantitate.setVisible(false);
                    tab1LbAv.setText("");
                    }
            }
            else {
                jPanelBilete.setVisible(false);
                
                tab1LbAv.setText(String.format("Acest CNP: %s exista in baza de date!", tab1TfCnp.getText().strip()));
                }
        } catch (SQLException ex) {
            Logger.getLogger(TicketsSystemManagement.class.getName()).log(Level.SEVERE, null, ex);
            jPanelBilete.setVisible(false);
        }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketsSystemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketsSystemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketsSystemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketsSystemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new TicketsSystemManagement().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TicketsSystemManagement.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TicketsSystemManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBilete;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel tab1;
    private javax.swing.JButton tab1BtnPlateste;
    private javax.swing.JComboBox<String> tab1ComboIteme;
    private javax.swing.JLabel tab1LbAv;
    private javax.swing.JLabel tab1LbCantitate;
    private javax.swing.JTextPane tab1TfCnp;
    private javax.swing.JTextPane tab1TfEmail;
    private javax.swing.JTextPane tab1TfNume;
    private javax.swing.JTextPane tab1TfPrenume;
    private javax.swing.JTextPane tab1TfTelefon;
    private javax.swing.JPanel tab2;
    private javax.swing.JButton tab2BtnActiveaza;
    private javax.swing.JButton tab2BtnDelete;
    private javax.swing.JButton tab2BtnSave1;
    private javax.swing.JButton tab2ButtVerifica;
    private javax.swing.JTextField tab2EmailTf;
    private javax.swing.JPanel tab2Jpanel;
    private javax.swing.JLabel tab2LbNume;
    private javax.swing.JLabel tab2LbPrenume;
    private javax.swing.JLabel tab2RaspLb;
    private javax.swing.JTextField tab2TelefonTf;
    private javax.swing.JTextField tab2Tf1;
    private javax.swing.JTextField tab2Tf2;
    private javax.swing.JTextField tab2Tf3;
    private javax.swing.JTextField tab2TfCnp;
    // End of variables declaration//GEN-END:variables
}
